services:
  postgres:
    image: postgres:17.3-bookworm
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./data:/opt/data
    tty: true
    ports:
      - 5432:5432
  
  pgadmin:
    image: elestio/pgadmin:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - 8080:8080
